server:
  port: 8083
#  servlet:
#    context-path: "/v1"
spring:
  application:
    name: product-service
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
eureka:
  client:
    serviceUrl:
#      defaultZone: http://eureka:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
#    preferIpAddress: true
    hostname: localhost
    ipAddress: 127.0.0.1
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"
springfox:
  documentation:
    swagger:
      v2:
        path: "/api-docs"
logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG