version: "2"
services:
  mongodb:
    image: mongo:3
    ports:
     - "127.0.0.1:27017:27017"
     - "127.0.0.1:28017:28017"
     - "127.0.0.1:28018:28018"
    expose:
     - "27017"
     - "28017"
     - "28018"
    command: mongod --smallfiles
  eureka:
    image: vislab-eureka
    ports:
     - "127.0.0.1:8761:8761"
    expose:
     - "8761"
  auth-service:
    image: vislab-eureka
    ports:
     - "127.0.0.1:8081:8081"
    expose:
     - "8081"
  gateway-service:
    image: vislab-zuul
    depends_on:
     - eureka
     - auth-service
    ports:
     - "127.0.0.1:9090:9090"
    expose:
     - "9090"
    environment:
      SPRING_APPLICATION_NAME: gateway-service
      SPRING_PROFILES_ACTIVE: enableEureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
  category-service:
    image: vislab-category-core
    depends_on:
     - mongodb
     - eureka
     - auth-service
    ports:
     - "127.0.0.1:8082:8080"
    expose:
     - "8080"
    environment:
      SPRING_APPLICATION_NAME: category-service
      SPRING_PROFILES_ACTIVE: enableEureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_SLEUTH_ENABLED: "true"
  product-service:
    image: vislab-product-core
    depends_on:
     - mongodb
     - eureka
     - auth-service
    ports:
     - "127.0.0.1:8083:8080"
    expose:
     - "8080"
    environment:
      SPRING_APPLICATION_NAME: product-service
      SPRING_PROFILES_ACTIVE: enableEureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_SLEUTH_ENABLED: "true"
  user-service:
    image: vislab-user-core
    depends_on:
     - mongodb
     - eureka
     - auth-service
    ports:
     - "127.0.0.1:8084:8080"
    expose:
     - "8080"
    environment:
      SPRING_APPLICATION_NAME: user-service
      SPRING_PROFILES_ACTIVE: enableEureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_SLEUTH_ENABLED: "true"
  product-comp-service:
    image: vislab-product-comp
    depends_on:
     - eureka
     - product-service
     - category-service
     - auth-service
    ports:
     - "127.0.0.1:8087:8088"
    expose:
     - "8088"
    environment:
     SPRING_APPLICATION_NAME: product-comp-service
     SPRING_PROFILES_ACTIVE: enableEureka
     EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
  user-proxy:
    image: vislab-user-proxy
    depends_on:
     - eureka
     - user-service
     - auth-service
    ports:
     - "127.0.0.1:8088:8088"
    expose:
     - "8088"
    environment:
      SPRING_APPLICATION_NAME: user-proxy-service
      SPRING_PROFILES_ACTIVE: enableEureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
  webapp:
    image: vislab-webapp
    depends_on:
     - eureka
     - gateway-service
     - user-service
     - user-proxy
     - product-service
     - product-comp-service
     - category-service
     - auth-service
    ports:
     - "127.0.0.1:8888:8080"
    expose:
     - "8080"


