version: "3"
services:
  mongodb:
    image: mongo:3
    ports:
     - "27017:27017"
     - "28017:28017"
     - "28018:28018"
    command: mongod --smallfiles
  eureka:
    image: vislab-eureka
    ports:
     - "8761:8761"
  gateway-service:
    image: vislab-zuul
    depends_on:
     - eureka
    ports:
     - "8081:9090"
    links:
     - eureka
    environment:
      SPRING_APPLICATION_NAME: gateway-service
      SPRING_PROFILES_ACTIVE: enableEureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://vislab-eureka:8761/eureka/
  category-service:
    image: vislab-category-core
    depends_on:
     - mongodb
     - eureka
    ports:
     - "8080:8082"
    links:
     - eureka
     - mongodb
    environment:
      SPRING_APPLICATION_NAME: category-service
      SPRING_PROFILES_ACTIVE: enableEureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_SLEUTH_ENABLED: "true"
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/vislab
  product-service:
    image: vislab-product-core
    depends_on:
     - mongodb
     - eureka
    ports:
     - "8080:8083"
    links:
     - eureka
     - mongodb
    environment:
      SPRING_APPLICATION_NAME: product-service
      SPRING_PROFILES_ACTIVE: enableEureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_SLEUTH_ENABLED: "true"
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/vislab
  user-service:
    image: vislab-user-core
    depends_on:
     - mongodb
     - eureka
    ports:
     - "8080:8084"
    links:
     - eureka
     - mongodb
    environment:
      SPRING_APPLICATION_NAME: user-service
      SPRING_PROFILES_ACTIVE: enableEureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_SLEUTH_ENABLED: "true"
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/vislab
  product-comp-service:
    image: vislab-product-comp
    depends_on:
     - eureka
     - product-service
     - category-service
    ports:
     - "8088:8089"
    links:
     - eureka
     - product-service
     - category-service
    environment:
     SPRING_APPLICATION_NAME: product-comp-service
     SPRING_PROFILES_ACTIVE: enableEureka
     EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
  user-proxy:
    image: vislab-user-proxy
    depends_on:
     - eureka
     - user-service
    ports:
     - "8088:8088"
    links:
     - eureka
     - user-service
    environment:
      SPRING_APPLICATION_NAME: user-proxy-service
      SPRING_PROFILES_ACTIVE: enableEureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
  webapp:
    image: vislab-webapp
    depends_on:
     - eureka
     - gateway-service
     - user-service
     - user-proxy
     - product-service
     - product-comp-service
     - category-service
    ports:
     - "8080:8080"
    links:
      - eureka
      - gateway-service
      - user-service
      - user-proxy
      - product-service
      - product-comp-service
      - category-service

