server:
  port: 8087
spring:
  application:
    name: user-proxy-service
eureka:
  client:
    serviceUrl:
#      defaultZone: http://eureka:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
#    preferIpAddress: true
    hostname: localhost
    ipAddress: 127.0.0.1
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health
logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8081/auth/user