/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen Do not edit the class manually.
 */
package de.hska.vislab.micro.api;

import de.hska.vislab.model.Role;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.constraints.Min;

@javax.annotation.Generated(
        value = "io.swagger.codegen.languages.SpringCodegen",
        date = "2018-05-09T06:42:04.687Z"
)
@Api(value = "role", description = "the role API")
public interface RoleApi {

    @ApiOperation(
            value = "Find role by level",
            nickname = "findRolebyLevel",
            notes = "",
            response = Role.class,
            authorizations = {
                    @Authorization(
                            value = "store_auth",
                            scopes = {}
                    )
            },
            tags = {
                    "role",
            }
    )
    @ApiResponses(
            value = {
                    @ApiResponse(code = 200, message = "successful operation", response = Role.class),
                    @ApiResponse(code = 400, message = "Invalid level supplied")
            }
    )
    @RequestMapping(
            value = "/role/{level}",
            produces = {"application/json"},
            method = RequestMethod.GET
    )
    ResponseEntity<Role> getRoleByLevel(
            @Min(1)
            @ApiParam(value = "Level of the role that needs to be found", required = true)
            @PathVariable(value = "level", required = true)
                    int level);
}
