server:
  port: 9090
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
zuul:
  host:
    connect-timeout-millis: 5000
    socket-timeout-millis: 10000
  ignoredServices: '*'
  routes:
    user-proxy-service: /user-proxy-service/**
    category-service: /category-service/**
    product-comp-service: /product-comp-service/**
    product-service: /product-service/**
    user-service: /user-service/**